### ISSUE TITLE
Version mismatched between GitHub Repo vs Terraform Registry

### ISSUE THREAD

**Issue by vaibhav-yenorkar** [salesforce/terraform-provider-anypoint#88]
Github release version for Terraform Anypoint Provider is 1.5.2 (released in Feb 2023). However latest version on Terraform Registry site for Terraform Anypoint Provider is 1.6.1.

So it does not seem we have latest code on Github repo. Can you please check and verify ?

**Comment by sabsfdc** [comment]
<img width="733" alt="Screenshot 2024-08-27 at 09 56 02" src="https://github.com/user-attachments/assets/04c3431f-9267-4f47-9eef-cfbec7afa990">

Hi @vaibhav-yenorkar  - please check the url of the source code. The terraform provider is built from a staging org (mulesoft-anypoint forked from the Salesforce org) as Salesforce github cannot be linked onto Hashicorp scanners due to security reasons. The community contributors of the staging github org (mulesoft-anypoint) do raise pull requests at times.

**Comment by vaibhav-yenorkar** [comment]
This is helpful, thanks @sabsfdc for pointing it out.
